### ISSUE TITLE
[Bug] 'File' translation problem

### ISSUE THREAD

**Issue by rlevet** [Hexer10/SPCode#55]
REQUIRE_PLUGIN doesn't appear in purple (by default) anymore

Translation "File" for the first menu doesn't work, and still displays "File" even though I set language to french

SPEdit:
![image](https://user-images.githubusercontent.com/36737524/106287369-fbffa500-6246-11eb-97e6-89258619c1b9.png)

SPCode:
![image](https://user-images.githubusercontent.com/36737524/106287307-f1451000-6246-11eb-8bd0-a991dfc6ef32.png)

**Comment by ratawar** [comment]
Thank you a lot for reporting

**Comment by Natanel-Shitrit** [comment]
Thanks for pointing this out.
Next time please open a issue for each problem, so it will be easier for us to track the changes and continue to maintain the program correctly, thank you!

**Comment by rlevet** [comment]
As these were pretty small problems I thought it would be better to but them together but y, no problem

**Comment by Natanel-Shitrit** [comment]
They are small problems but for the sake of organization it's better to have discussion and tagging for individual problem, and this is a great example because we (SPCode maintainers) didn't decide what to do yet with the `#define` problem because we need to discuss how to fix it and for example what is the best approach, but the second problem is minor issue that i fixed immediately so now i added the `fixed` label and it can cause confusion because 1 problem got fixed and 1 doesn't.

I hope because of that we will add some ground rules for new issues.
Something good came out from this problem, so thanks!

**Comment by ratawar** [comment]
I will re-do this issue - this one will remain as a report of the "File" string translation bug, marked as solved and closed. Thanks a lot! Please keep them reports coming.
